# Generated by Django 4.2.3 on 2023-07-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('description', models.CharField(max_length=255)),
                ('lang_back', models.CharField(max_length=125)),
                ('lang_front', models.CharField(max_length=125)),
                ('dev_site', models.CharField(max_length=125)),
                ('prod_site', models.CharField(max_length=125)),
                ('doc_site', models.CharField(max_length=125)),
                ('server', models.CharField(max_length=125)),
                ('pub_date', models.DateField()),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['name'],
            },
        ),
    ]
