# Generated by Django 4.1.7 on 2023-07-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('1', 'Principal'), ('2', 'Suplente')], default='1', max_length=1)),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('dev_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('1', 'Desarrollador'), ('2', 'Soporte')], default='1', max_length=1)),
                ('status', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='application_id',
            new_name='app_id',
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1),
        ),
    ]
